Merges gitbook documentation
Exerra-Discord/karen-bot-docs pull request #14
Opened 2021-07-30 22:27 UTC by Exerra

This PR will merge gitbook documentation with these docs. Currently a few simple things are added but I will need to spruce it up

2021-07-30 22:58 UTC, Exerra commented
The main content is here. Now I will need to migrate the new settings JSON to my API and, well, spruce the new sections up a bit.

2021-07-30 23:01 UTC, Amiichuu reviewed
So far so good, I suggest sprucing it up a bit. Maybe display the swear words and crypto in a table?

2021-07-31 08:29 UTC, Exerra commented
> So far so good, I suggest sprucing it up a bit. Maybe display the swear words and crypto in a table?

Thought about it, but ngl unless there are going to be severity options, having a one column table is weird

2021-07-31 08:37 UTC, Amiichuu requested changes
Please change the things I provided and re-request review when you're done

2021-07-31 08:37 UTC, Amiichuu commented on users/supportedCrypto.md
> +> Didn't know Karen rejected fiat currencies too
Change this to "Karen Bot"

2021-07-31 08:37 UTC, Amiichuu commented on users/supportedCrypto.md
> +... and their short versions (e.g btc, eth and so on)!
Capitalize the short versions

2021-07-31 08:37 UTC, Amiichuu commented on users/swearWords.md
> +> Karen filters swear words? Oh the irony
Again, branding

2021-07-31 08:37 UTC, Amiichuu commented on users/swearWords.md
> +So this section focuses on the swear words Karen Bot filters if you have "AntiSwear" enabled in the settings (by default it is off). All of these messages result in a deletion of the message and a...
Link "settings" to `users/settings.md`

2021-07-31 08:40 UTC, Exerra commented on users/supportedCrypto.md
> +> Didn't know Karen rejected fiat currencies too
Forgot about that
Done

2021-07-31 08:40 UTC, Exerra commented on users/supportedCrypto.md
> +... and their short versions (e.g btc, eth and so on)!
Done

2021-07-31 08:45 UTC, Amiichuu approved these changes
Issues are now fixed, approved

2021-07-31 08:45 UTC, Amiichuu commented on users/swearWords.md
> +So this section focuses on the swear words Karen Bot filters if you have "AntiSwear" enabled in the [settings](users/settings.md) (by default it is off). All of these messages result in a deletion of
It works with docsify, so no

2021-07-31 08:46 UTC, merged